server:
  port: 18851
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xchuang-li/config-infomation.git
          ###有时，配置文件可能在仓库的子目录下，此配置可以搜索对应的子目录，如foo,bar*
          search-paths: /**
          username: xchuang-li
          password: Lcay110802
          ###默认在第一次请求时克隆仓库，此配置可在启动时就克隆仓库
          clone-on-start: true
        ###全局默认仓库分支，也可以写在对应匹配模式下
        default-label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
