server:
  port: 18812
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
  instance:
    metadata-map:
      cluster: PEOPLE
spring:
  application:
    name: people-provider-ha
movie-provider:
  ribbon:
    ###负载均衡策略 -轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ###每台服务器最多重试次数，首次调用不计算在内
    MaxAutoRetries: 1
    ###最多重试多少台服务器
    MaxAutoRetriesNextServer: 1
    ###无论是超时或socket read Timeout都进行重试
    OkToRetryOnAllOperations: true
    ###Interval to refresh the server list from the source
    ServerListRefreshInterval: 2000
    ###Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    ###Read timeout used by Apache HttpClient
    ReadTimeout: 3000
###预加载配置 默认为懒加载
ribbon:
  eager-load:
    enabled: true
    clients: movie-provider
logging:
  level:
    com.lcay.cloud.feign: debug
feign:
  client:
    config:
      default:
        connectTimeout: 5000 #连接超时
        readTimeout: 5000 #读取超时
        loggerLevel: full #日志级别
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
