server:
  port: 18801
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis:
  type-aliases-package: com.lcay.cloud.mapper
logging:
  level:
    com.lcay.cloud.mapper: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cay?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=true
    username: root
    password: root
  application:
    name: movie-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true