server:
  port: 18801
spring:
  application:
    name: sleuth-service-sent
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest